### ISSUE TITLE
Auth/Redirect Infinite Loop

### ISSUE THREAD

**Issue by jburgoyn** [AntonioErdeljac/next14-miro-clone#1]
While following along with the tutorial, once I got the Clerk Provider all set up and tried to run it, it would redirect to the Clerk authentication as expected, but then once I logged in, it entered a auth/redirect loop. I double checked everything and couldnt find anything different, so I cloned the final project, added my creds, and it had the same issue. Not sure if it is a Clerk version difference? Here are some links to others having same issue.

https://jeremysawesome.com/2024/01/12/clerk-auth-redirect-reload-loop/
https://github.com/clerk/javascript/issues/1436

I was only able to get it to work by signing in, letting it go into the auth loop. Then stopping the server, and adding this to the middleware:

```
export default authMiddleware({
  publicRoutes: ["/"],
});
```
 
This would then load the application with the logged in credentials. This only works as a hack though.

Error in console log:
The <SignUp/> and <SignIn/> components cannot render when a user is already signed in, unless the application allows multiple sessions. Since a user is signed in and this application only allows a single session, Clerk is redirecting to the Home URL instead.
(This notice only appears in development)

**Comment by jburgoyn** [comment]
From a comment on the video, looks like this also fixes it:

export default authMiddleware({
  publicRoutes: ["/"],
  ignoredRoutes: ["/((?!api|trpc))(_next.*|.+.[w]+$)", "/"],
});

**Comment by AntonioErdeljac** [comment]
hi, can you try clearing the cookies? this resolved the issue for a lot of people, seems like something happened with clerk dev envs and they pushed a fix today

**Comment by jburgoyn** [comment]
Awesome, I updated the package, and it seems to be working now. Thanks so much for the awesome courses!
