### ISSUE TITLE
Switching favorite boards and searching for matches does not work in deployment environment

### ISSUE THREAD

**Issue by CarryWang** [AntonioErdeljac/next14-miro-clone#10]
Hello Antonio,

Thank you for this amazing project.

I'm building my own version of miro clone based on your tutorial.

[https://miro.carrywang.xyz/](https://miro.carrywang.xyz/)

However, when using vercel to deploy to an online environment, it was found that switching favorite boards and search input did not work, but everything worked fine in the local environment, and the code was the same for both environments.

My guess is that it may be related to the front-end routing, I'm not sure if I need to set up a separate route or something on an online environment. And I am not sure whether it is related to convex. After searching some information, I did not find the answer.

---

###  local environment：Click favorite button to respond correctly and also see the request
![image](https://github.com/AntonioErdeljac/next14-miro-clone/assets/12207994/6297d1f5-9715-4fe4-a639-1c95065cd372)
###  vercel environment：When click favorite button, the UI does not respond and does not see the request
![image](https://github.com/AntonioErdeljac/next14-miro-clone/assets/12207994/350e4296-7383-4f38-9890-44905641037f)
###  local environment：Search keywords and have the right response
![image](https://github.com/AntonioErdeljac/next14-miro-clone/assets/12207994/bcce13b3-bb44-4abb-be35-9d04d3f01ba2)
###  vercel environment：Search keyword, there is a request, but no UI response
![image](https://github.com/AntonioErdeljac/next14-miro-clone/assets/12207994/1d98612a-b500-4aa9-ab44-8a0a4a997634)

---

**Comment by Ian-Chege** [comment]
@CarryWang here's the fix;

Solution: https://github.com/AntonioErdeljac/next14-miro-clone/commit/8decc718c93b9e70eb997977e01fb09b84e486c3

Refactor the dashboard page to use `useSearchParams` for search and favorites.

**Comment by CarryWang** [comment]
it worked! 🎉

@Ian-Chege Thanks for your help👍
