### ISSUE TITLE
About useDebounce was abandoned

### ISSUE THREAD

**Issue by mus3000** [AntonioErdeljac/next14-miro-clone#8]
I am a newbie who just learned. When I followed the instructions, I found that useDebounce has been deprecated. It has been replaced by useDebounceValue and useDebounceCallback. However, my ability is limited, and English is not my mother tongue. I want to know how to implement it in the code. Same logic.

Thank a lot. 

```
"use client";

import qs from "query-string";
import { Search } from "lucide-react";
import { useDebounce } from "usehooks-ts";
import { useRouter } from "next/navigation";
import {
  ChangeEvent,
  useEffect,
  useState,
} from "react";

import { Input } from "@/components/ui/input";

export const SearchInput = () => {
  const router = useRouter();
  const [value, setValue] = useState("");
  const debouncedValue = useDebounce(value, 500);

  const handleChange = (e: ChangeEvent<HTMLInputElement>) => {
    setValue(e.target.value);
  };

  useEffect(() => {
    const url = qs.stringifyUrl({
      url: "/",
      query: {
        search: debouncedValue,
      },
    }, { skipEmptyString: true, skipNull: true });

    router.push(url);

  }, [debouncedValue, router]);




  return (
    <div className="w-full relative">
      <Search
        className="absolute top-1/2 left-3 transform -translate-y-1/2 text-muted-foreground h-4 w-4"
      />
      <Input
        className="w-full max-w-[516px] pl-9"
        placeholder="Search boards"
        onChange={handleChange}
        value={value}
      />
    </div>
  );
};
```

**Comment by Ian-Chege** [comment]
Using `useDebounceValue` 

![image](https://github.com/AntonioErdeljac/next14-miro-clone/assets/107269298/61e88842-f2f9-48f4-bc42-10575a94e7d2)

**Comment by erwaf444** [comment]
Thank you for your reply. I have another question. When I went further, I found that there was a problem with both my query.search and query.favorites, which caused me to be unable to use 
`{query.favorites in board-list.tsx. ? "Favorite boards" : "Team boards"}`

the error like:

Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'favorites')

**Comment by GreNxNja** [comment]
![image](https://github.com/AntonioErdeljac/next14-miro-clone/assets/101276010/3c81ebf9-6d5e-4919-a578-cb011ba7230f)


Search might throw an error so i ve initiated this

**Comment by mus3000** [comment]
thank you for help !

**Comment by kool7** [comment]
This issue can be closed now. @AntonioErdeljac
